# Template: Docker Publish
# Description: Docker template to publish applications with CI/CD

name: publish
on:
  push:
    branches: ["main"]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/${{ github.actor }}/default-repo:latest
jobs:
  publish:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        run: |
          echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and Push Docker Image
        run: |
          docker build . --tag ${{ env.IMAGE_NAME }}
          docker push ${{ env.IMAGE_NAME }}
  deploy:
    needs: publish
    name: Deploy Image
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
      - name: Pull and Deploy Docker Image
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && docker compose pull && docker compose up -d"
      - name: Cleanup SSH Keys
        run: rm -rf ~/.ssh
